- name: Install development tools and libraries
  dnf:
    name:
      # Groups with useful tools like rpmbuild, make, etc.
      - '@C Development Tools and Libraries'
      - '@Development Tools'
      - '@RPM Development Tools'
      # Some CLI utilities for convenient usage
      - 'bash-completion'
      - 'zsh'
      - 'fish'
      - 'vim'
      - 'tig'
      - 'htop'
      - 'tmux'
      - 'fd-find'
      - 'ripgrep'
      - 'tree'
      - 'nc'
      # For macOS
      - 'virtualbox-guest-additions'
      # Specific to this project
      - 'npm'
      - 'python2'
      - 'podman'
    state: present
